#!/bin/sh
# Notes:
# - arguments: "assembleRelease" to build APK, "installRelease" to build APK and install on connected device
# - to view log messages from just Maps:
#  /home/mwhite/android-sdk/platform-tools/adb logcat | grep -e Tangram -e StylusLabs

set -e

if [ "$1" = "--install-sdk" ]; then
  java --version || sudo apt install openjdk-17-jdk
  mkdir $HOME/android-sdk && pushd $HOME/android-sdk
  curl https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip --output cmdline-tools.zip
  unzip cmdline-tools.zip
  cmdline-tools/bin/sdkmanager --sdk_root=. --install 'build-tools;34.0.0' 'platforms;android-34' 'platform-tools' 'ndk;26.3.11579264' 'cmake;3.18.1'
  #cmdline-tools/bin/sdkmanager --sdk_root=. --install 'build-tools;30.0.3' 'platforms;android-30' 'platform-tools' 'ndk;23.1.7779620' 'cmake;3.18.1'
  popd
  exit 0
fi

# gradle expects people to add their binary file to git!  And doesn't provide a way to just download gradle wrapper!
# ... other gradle wrapper wrappers do crazy things like download the entire gradle dist (>100MB) to install the wrapper,
#  which will in turn download gradle again!  And why is gradle-wrapper.jar 60KB when it just downloads and runs another
#  program, which this script accomplishes in a few lines?
if [ ! -f ./gradlew ]; then
  mkdir -p ./gradle/wrapper
  # we need to specify gradle version in gradle-wrapper.properties
  #curl 'https://raw.githubusercontent.com/libsdl-org/SDL/main/android-project/gradle/wrapper/gradle-wrapper.properties' --output ./gradle/wrapper/gradle-wrapper.properties
  curl 'https://raw.githubusercontent.com/libsdl-org/SDL/main/android-project/gradle/wrapper/gradle-wrapper.jar' --output ./gradle/wrapper/gradle-wrapper.jar
  curl 'https://raw.githubusercontent.com/libsdl-org/SDL/main/android-project/gradlew' --output gradlew
  chmod 755 gradlew
fi

[ -z "$ANDROID_HOME" ] && export ANDROID_HOME="$HOME/android-sdk"
./gradlew "$@"
