# Stylus Labs Maps config
sources:
  file: mapsources.yaml
  last_source: opentopomap
  elevation: ["elevation"]
  common_imports:
    - scenes/markers.yaml
    #- scenes/secrets.yaml
  list_order:
    - stylus-osm-terrain
    - stylus-bike-hike
    - stylus-satellite
    - stylus-worldcover
    - enable-slope-angle
    - enable-contours
    - hillshade
    - hillshade-usgs
    - opentopomap
    - arcgis-satellite
    - bing-earth
    - esa-sentinel2
    - nasa-worldview
    - worldcover
    - usgs-imagery
    - usgs-topo
    - archived

terrain_3d:
  enabled: true
  import: scenes/terrain-3d.yaml
  updates:
    global.earth_style: terrain-3d-polygons

# use https://github.com/aosp-mirror/platform_frameworks_base/raw/de0fe2daafb769cc37ca922ffef6dbafb8c6cae2/data/fonts/DroidSansFallback.ttf because next version removes a bunch of characters
fallback_fonts:
  - shared/fonts/Roboto-Regular.ttf
  - shared/fonts/DroidSansFallback.ttf

storage:
  # cache size thresholds (MB) - set to 0 for no limit
  shrink_at: 600
  shrink_to: 400
  # immediately delete tiles when deleting offline map?
  purge_offline: true
  # max number of simultaneous download requests
  offline_download_rate: 20
  #import_pois: true  -- default is true
  #export_pois: true  -- default is false
  #max_age: 31104000  -- max cached tile age; default is 180 days = 15552000 seconds

view:
  #lng: -122.434668
  #lat: 37.776444
  zoom: 15

search:
  min_poi_zoom: 19
  hide_bookmarks: false
  download_url: "https://github.com/styluslabs/maps/?tab=readme-ov-file#generating-tiles"

tracks:
  # default to valhalla plugin
  plugin: 1
  # point added to track if min_distance (m) OR min_time (sec) from last point; this sets density of points
  min_distance: 0.5
  min_time: 5
  # Android leaves GPS on continuously if sample_period (sec) is less than 10 seconds
  sample_period: 0.1

metric_units: true

# set global.shuffle_seed to random value each time app is run (can be used, e.g., to randomize POI priorities)
random_shuffle_seed: true

# color choices for tracks and markers; from https://colorkit.co
# ["#1abc9c","#16a085","#2ecc71","#27ae60","#3498db","#2980b9","#9b59b6","#8e44ad","#34495e","#2c3e50","#f1c40f","#f39c12","#e67e22","#d35400","#e74c3c","#c0392b"]
colors: ["#1ABC9C", "#27AE60", "#2980B9", "#9B59B6", "#F1C40F", "#F39C12", "#D35400"]

ui:
  #show_debug: true
  reverse_map_btns: false
  #font: "scenes/fonts/NotoSans-Regular.ttf"
  theme: light
  ui_scale: 0.95
  map_scale: 0.95

#tile_cache_limit: 536870912

# for debugging
num_tile_workers: 2

msaa_samples: 2
