# (mostly) project-independent Makefile fragment for Android
# refs:
# - https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md

# common C and C++ flags
CFLAGS += -MMD -fPIC -fvisibility=hidden -ffunction-sections -fdata-sections -Wall -Werror=return-type -Wno-strict-aliasing
NDK_PREBUILT := $(wildcard $(ANDROID_NDK)/toolchains/llvm/prebuilt/*)
# C++
CXX = $(NDK_PREBUILT)/bin/clang++ --target=aarch64-linux-android21
CXXFLAGS += --std=c++14 -fexceptions -frtti
# C
CC = $(NDK_PREBUILT)/bin/clang --target=aarch64-linux-android21
CCFLAGS += --std=c99 -Werror=implicit-function-declaration -Werror=int-conversion
# linker
LD = $(CXX) -shared
LDFLAGS += --std=c++14 -static-libstdc++ -fexceptions -frtti -fPIC -fvisibility=hidden -Wl,-soname,$(TARGET) -Wl,--exclude-libs,ALL -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections
# strip/objcopy; alternatively, we could let gradle strip library
STRIP = $(NDK_PREBUILT)/bin/llvm-strip -s


DEBUG ?= 0
ifneq ($(DEBUG), 0)
  CFLAGS += -O0 -g -DDEBUG
  # rdynamic needed to get backtrace symbols from, e.g., catchsegv
  LDFLAGS += -rdynamic
else
  # use ffunction-sections + gc-sections to remove unused functions
  CFLAGS += -O2 -g -DNDEBUG
  LDFLAGS += -O2
endif

# project independent stuff

# assumes *FLAGS variables use deferred evaluation
CFLAGS += $(CFLAGS_PRIVATE)
CCFLAGS += $(CCFLAGS_PRIVATE)
CXXFLAGS += $(CXXFLAGS_PRIVATE)

# include files
INCFLAGS = $(INC:%=-I%) $(INC_PRIVATE:%=-I%) $(INCSYS:%=-isystem %) $(INCFILES:%=-include %)

# defines
CFLAGS += $(DEFS:%=-D%) $(DEFS_PRIVATE:%=-D%)

SRCBASE=$(basename $(SOURCES))
OBJ=$(SRCBASE:%=$(OBJDIR)/%.o)
DEPS=$(SRCBASE:%=$(OBJDIR)/%.d)
TGT=$(BUILDDIR)/$(TARGET)
# gcc will not create directories, so depend on existence of all directories in output folder
# sort removes duplicates (which cause make error)
BUILDDIRS=$(sort $(dir $(OBJ)))

.PHONY: all stripped clean sourcelist

all: $(TGT)

stripped: $(OUTPUT)

$(OUTPUT): $(TGT)
	mkdir -p $(dir $(OUTPUT))
	$(STRIP) -o $@ $<

$(OBJDIR)/%.o: %.cpp
	$(CXX) -c $(CFLAGS) $(CXXFLAGS) $(INCFLAGS) -o $@ $<

$(OBJDIR)/%.o: %.cc
	$(CXX) -c $(CFLAGS) $(CXXFLAGS) $(INCFLAGS) -o $@ $<

$(OBJDIR)/%.o: %.c
	$(CC) -c $(CFLAGS) $(CCFLAGS) $(INCFLAGS) -o $@ $<

$(TGT): $(OBJ)
	$(LD) -o $@ $^ $(LDFLAGS) $(LIBS:%=-l%)

# files that need to be generated, downloaded, etc.
$(OBJ): $(GENERATED)

# | (pipe) operator causes make to just check for existence instead of timestamp
$(OBJ): | $(BUILDDIRS)

$(BUILDDIRS):
	mkdir -p $(BUILDDIRS)

clean:
	rm -f $(TGT) $(OBJ) $(DEPS)

sourcelist:
	@printf '%s\n' $(SOURCES)

# dependency files generated by gcc (-MMD switch) ("-include" ignores file if missing)
-include $(DEPS)
